### ISSUE TITLE
Feature Request: Bổ sung tính năng chuyển đổi bộ gõ tự động trong VIM

### ISSUE THREAD

**Issue by kiemrong08** [ZeroX-DG/vi-rs#1]
Mô tả: Khi ở trong Insert Mode thì tự động bật chế độ gõ Tiếng Việt.
Khi quay trở lại Normal mode thì tự động tắt bộ gõ.

**Comment by ZeroX-DG** [comment]
Issue này chắc cũng k còn liên quan nữa tại mình repurpose cái project thành library rồi 😄 
Bộ gõ bây giờ được phát triển ở đây: https://github.com/huytd/goxkey

Nên chắc mình sẽ đóng issue này.
