### ISSUE TITLE
Thiếu tính năng bỏ dấu tự do

### ISSUE THREAD

**Issue by jason-nguyen17** [ZeroX-DG/vi-rs#13]
Ví dụ bỏ dấu tự do, bỏ dấu ở cuối từ
Con cuuwf -> Con cừu 
Thay vì bỏ dấu ngay sau nguyên âm
Con cuwuf -> Con cừu

**Comment by ZeroX-DG** [comment]
Fixed in https://github.com/ZeroX-DG/vi-rs/commit/bf6c5cae7a62b695f3153f2829236dc1a50b949c
