### ISSUE TITLE
Lỗi khi gõ chữ "Hợac"

### ISSUE THREAD

**Issue by huytd** [ZeroX-DG/vi-rs#15]
hợac
hợac
hợac
hợac
ho ặc

yeah, that's it

hoặc

![image](https://user-images.githubusercontent.com/613943/216889547-97cd282d-5627-46ef-afe2-7bbe4ef3049c.png)

**Comment by ZeroX-DG** [comment]
4 days later. I still don't know how to fix this bug 😂
