### ISSUE TITLE
Panic in transform_buffer 

### ISSUE THREAD

**Issue by huytd** [ZeroX-DG/vi-rs#27]
After v0.3.7, we got a few panic cases, for example, when the user typing "land" in Telex mode: 

```
thread '<unnamed>' panicked at 'Couldn't retrieve replace char for l for Dyet', vi-rs-5b567bc8b512911b/83317ad/src/processor.rs:185:36
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Ideally `transform_buffer` should not be panicked, but in case it is, we probably want to make it a function returning a Result, so the caller side can handle it.

https://github.com/huytd/goxkey/issues/42

**Comment by ZeroX-DG** [comment]
Nice catch! Fixed in https://github.com/ZeroX-DG/vi-rs/commit/b671c70a5532921eb326368f1c565c47a590f798
