### ISSUE TITLE
bug: telex: consecutive d's stucks at đd

### ISSUE THREAD

**Issue by quangngd** [ZeroX-DG/vi-rs#30]
# Reproduce

```rust
fn main() {
    let mut result = String::new();
    for n in 1..10 {
        let mut input = Vec::new();
        for _ in 0..n {
            input.push('d');
        }
        vi::telex::transform_buffer(input.iter().cloned(), &mut result);
        result.push('\n');
    }
    println!("{}", result);
}
```
- Expect (similar to consecutive a's)
```
d
đ
dd
ddd
dddd
...
```
- Actual
```
d
đ
dd
đd
đd
đd
đd
đd
đd
```

# Cause

- `modify_letter` always add tone to the first `d`/`đ` --> stuck
- if i modified so that `modify_letter` add tone to the last `d`, then `reposition_letter_modification` will always reorder the modifications and put the tone back to the first `d`/`đ` --> stuck
- Finally `is_valid_word` does not recognize `dd` as an invalid word (like `aa`). Might be best to fix here.

**Comment by ZeroX-DG** [comment]
Thanks for reporting! Sorry for taking so long to get this fixed 😅
