### ISSUE TITLE
`transform_buffer` crashes when received unexpected input

### ISSUE THREAD

**Issue by faptc** [ZeroX-DG/vi-rs#31]
This code crashes unexpectedly:
```rust
    let mut out = String::new();
    let inp = "sdd";
    telex::transform_buffer(inp.chars(), &mut out);
```

I agree the input string is not valid. 
Could `transform_buffer` returns an explicit error to handle this case?
So that my process -- run as daemon -- doesn't exit early.

Thank advance for your considerations.

**Comment by ZeroX-DG** [comment]
Ah yeah, this is a case that I didn't think of. We should just ignore it instead of returning any error in this case. I'll make a fix for it.
