### ISSUE TITLE
A couple of typing issues

### ISSUE THREAD

**Issue by huytd** [ZeroX-DG/vi-rs#39]
Hiện tại có 1 issues trên GõKey từ khi up lên vi-rs bản 0.6.0:
- https://github.com/huytd/goxkey/issues/117

Ngoài ra còn có một vài issue khác nhưng a ko chắc có phải do vi-rs ko, có thể nó là do chức năng restore của GõKey, nhưng mà e check từ phía vi-rs thêm xem sao nhé.
- https://github.com/huytd/goxkey/issues/116
- https://github.com/huytd/goxkey/issues/112
- https://github.com/huytd/goxkey/issues/114

**Comment by tesuji** [comment]
Em vừa kiểm tra trên linux:
Lỗi https://github.com/huytd/goxkey/issues/117: không xuất hiện trên vi-rs. Test tại https://github.com/ZeroX-DG/vi-rs/blob/c1d3f1e317fb1a0c8790b39e20705ec4589413f7/testdata/input/simple_telex.txt#L67, kết quả https://github.com/ZeroX-DG/vi-rs/blob/c1d3f1e317fb1a0c8790b39e20705ec4589413f7/testdata/output/telex__simple_telex.snap#L73

Lỗi Level cũng thế. Gõ được bình thường không bỏ dấu.

**Comment by dvbthien** [comment]
Hi mn,
Lỗi  ww -> w nhưng lại ra ưw thì mình thấy có lúc gõ ww nó lại ra w đúng nhưng có lúc nó lại ra ưw nhưng trường hợp ra ưw lại nhiều hơn.
Còn lỗi level thì mình có test thử trên bản mới nhất thì thấy không bị nữa.
Thanks

**Comment by huytd** [comment]
Trường hợp ra đúng chắc là tại trước đó bạn nhấn nút Ctrl, trong GõKey thì khi nhấn nút Ctrl bộ gõ sẽ tạm tắt chế độ gõ tiếng Việt và khôi phục từ nguyên gốc (tương tự với nút Cmd thì sẽ commit từ vừa đc gõ mà ko cần nhấn space).

**Comment by ZeroX-DG** [comment]
@huytd Em vừa test mấy issue bên anh:

- https://github.com/huytd/goxkey/issues/116: Không có lỗi ở `vi-rs`. Em nghĩ case này chắc `goxkey` commit word sau khi người dùng gõ space bị lỗi đâu đó. Hoặc có khi ver mới fix cái bug này rồi.
- https://github.com/huytd/goxkey/issues/112: Không có lỗi ở `vi-rs`. Lỗi này cũng liên quan tới phím cách nên em nghĩ chắc do bên `goxkey`, vì `vi-rs` không xử lý phím cách.
- https://github.com/huytd/goxkey/issues/114: Không có lỗi ở `vi-rs`. Lỗi này khá dị vì output người dùng ra `llêl`, tức là mất chữ `v` và đúp chữ `l`??? Lỗi này chắc do lúc send backspace bị gì đúp hay gì đó 🤔 

Còn issue https://github.com/huytd/goxkey/issues/117 thì do trong PR https://github.com/ZeroX-DG/vi-rs/pull/37 `vi-rs` đã chuyển sang cơ chế xử lý `w` mới. Em không rõ cái cơ chế mới này đúng hay sai vì em không dùng telex. Em cần thu thập thêm ý kiến về vụ này. Nếu vấn đề ở đây không có đúng sai mà là vấn đề về sở thích, thói quen gõ khác nhau của mỗi người thì chắc em có thể bắt đầu cho phép nhiều cách gõ `w` khác nhau 🤔

**Comment by ZeroX-DG** [comment]
<img width="834" alt="Screenshot 2024-05-24 at 11 48 34 PM" src="https://github.com/ZeroX-DG/vi-rs/assets/12984316/070ba456-e842-4047-8d01-b04fa4e5aeba">
Unikey có vụ telex giản lược để w không chuyển thành `ư`... chắc phải thêm telex giản lược roài 😂

**Comment by huytd** [comment]
Liên quan tới https://github.com/huytd/goxkey/issues/116 và https://github.com/huytd/goxkey/issues/112 thì nó như này:

- User gõ `e1`, trên màn hình hiển thị `é`, typing buffer mà gõkey đang track lúc này là `e1`
- User gõ thêm số 1 để huỷ dấu, màn hình lúc này hiển thị `e1`, typing buffer mà gõkey đang track lúc này là `e11`
- User nhấn space, gõkey lúc này nhận thấy từ đang hiển thị là `e1` không phải là một từ tiếng việt hợp lệ (xài hàm `vi::validation::is_valid_word` của vi-rs), nên thực hiện replace từ đang gõ thành typing buffer là `e11`. 

Ở bước thứ 2 nếu gõkey biết được là vi-rs đã huỷ dấu, thì có thể chủ động sửa typing buffer từ `e11` thành `e1`, vậy nên có thể sửa hàm `vi::*::transform_buffer` của vi-rs để trả về thêm 1 cái flag khi nào thì vi-rs thực hiện restore/huỷ bỏ dấu của từ đang gõ đc ko nhỉ @ZeroX-DG ?

**Comment by ZeroX-DG** [comment]
@huytd `vi-rs` đã có trả về status đó rồi. Nhưng nó không public nên không ai đọc đc gì ráo 😂 
https://github.com/ZeroX-DG/vi-rs/blob/c1d3f1e317fb1a0c8790b39e20705ec4589413f7/src/lib.rs#L44-L52

`v0.6.1` sẽ public mấy field đó.

**Comment by huytd** [comment]
![](https://media3.giphy.com/media/Qumf2QovTD4QxHPjy5/200w.gif?cid=6c09b952xj02py9s5k00mls3xr79xkgxk61d8raz2edsf2fs&ep=v1_gifs_search&rid=200w.gif&ct=g)

**Comment by ZeroX-DG** [comment]
@huytd `v0.6.1` vừa ra lò nha anh 😄

**Comment by huytd** [comment]
ok ngon lành, thank e, để a update bên gõkey

**Comment by huytd** [comment]
Tạm thời toàn bộ các issue ở trên đã đc fix nên có thể close issue này đc rồi :D Thanks mọi người nha, và nhớ up lên gõkey v0.2.8 nhé.
