### ISSUE TITLE
Fix lỗi khi gõ 2 chữ A viết hoa (AA) không thể trở thành Â

### ISSUE THREAD

**Issue by jason-nguyen17** [ZeroX-DG/vi-rs#7]
Mình đang tìm hiểu rust và có xem qua project Gõ Key.
Loay hoay 1 hồi thì test ra bug bị ở project này.
Hiện tại khi mình test thì nếu gõ
- Aa -> Â 
- aa -> â
- AA -> AA
Mình tạm fix bằng cách compare to_ascii_lowercase cả 2 như hình thì test thấy ok.
<img width="392" alt="image" src="https://user-images.githubusercontent.com/11462491/216409296-fb7d4afc-8e19-4580-b4b5-4a73cc96e43c.png">

**Comment by ZeroX-DG** [comment]
À bạn tìm đúng bug rồi đó 😄  Ở cái function `contains_clean_char` đó mình luôn mặc định nghĩ rằng `ch` là lowercase char (`a`, `e`, hoặc `o`) mà lại quên pass lowercase char vào 😄 Bạn có thể contribute cái fix của bạn cho project này luôn k? 😄

**Comment by jason-nguyen17** [comment]
Được chứ, mình khá hứng thú với project này và goxkey.
Mình đang debug luôn cái issue triple A nữa, hi vọng là fix được rồi mình contribute luôn nhé.

**Comment by ZeroX-DG** [comment]
Ù nhất tiễn song điêu à 😄 Được luôn bạn ơi! Mình chờ PR của bạn 😄
