### ISSUE TITLE
Lỗi khi gõ A liên tục 3 lần thì sẽ thành ÂA chứ không trả lại thành AA

### ISSUE THREAD

**Issue by jason-nguyen17** [ZeroX-DG/vi-rs#8]
Lỗi này khi mình dùng goxkey để test.
Và mình đang buồn ngủ quá nên chưa tìm ra chỗ bị bug....

**Comment by ZeroX-DG** [comment]
Fixed in https://github.com/ZeroX-DG/vi-rs/commit/054d16dec06593ea757eecfd89a7bdc89447838a
